name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Pyinstaller
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller

      - name: Build
        run: make pyinstaller

      - name: Retrieve Version
        run: echo ::set-env name=COMMIT_HASH::$(git rev-parse HEAD | cut -c 1-8)

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: ${{ env.COMMIT_HASH }}
          files: dist/*
