name: Release

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Pyinstaller
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller

      - name: Build
        run: make pyinstaller

      - name: Release (Untagged)
        if: "!startsWith(github.ref, 'refs/tags/v')"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "Development Build"
          automatic_release_tag: "latest"
          prerelease: true
          files: dist/*

      - name: Release (Tagged)
        if: startsWith(github.ref, 'refs/tags/v') && github.ref == 'refs/heads/master'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: dist/*
